
package Component;

import Events.PublicEvent;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import Model.Model_user_account;

public class Item_people extends javax.swing.JPanel {
    
    private final Model_user_account user;
    private boolean mouseOver;

    public Model_user_account getUser() {
        return user;
    }    

    public Item_people(Model_user_account user) {
        this.user=user;
        initComponents();
        id.setText(user.getUserName());
        activeStatus.setActive(user.isStatus());
        init();
    }
    
    public void updateStatus(){
        activeStatus.setActive(user.isStatus());
    }
    
    private void init(){
        addMouseListener(new MouseAdapter(){
            @Override
            public void mouseEntered(MouseEvent e) {
                setBackground(new Color(242,242,242));
                mouseOver=true;
            }
            @Override
            public void mouseExited(MouseEvent e) {               
                setBackground(new Color(230,230,230));
                mouseOver=false;
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if(mouseOver){
                    PublicEvent.getInstance().getEventMain().selectUser(user);
                }
            }
            
            
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new swing.ImageAvatar();
        imageAvatar2 = new swing.ImageAvatar();
        imageAvatar3 = new swing.ImageAvatar();
        id = new javax.swing.JLabel();
        idStatus = new javax.swing.JLabel();
        activeStatus = new swing.ActiveStatus();

        setBackground(new java.awt.Color(230, 230, 230));
        setPreferredSize(new java.awt.Dimension(200, 50));

        imageAvatar3.setBorderSize(0);
        imageAvatar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N

        id.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        id.setText("Name");

        idStatus.setFont(new java.awt.Font("Helvetica Neue", 2, 12)); // NOI18N
        idStatus.setForeground(new java.awt.Color(139, 139, 139));
        idStatus.setText("new user");

        activeStatus.setActive(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(activeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addGap(6, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imageAvatar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ActiveStatus activeStatus;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idStatus;
    private swing.ImageAvatar imageAvatar1;
    private swing.ImageAvatar imageAvatar2;
    private swing.ImageAvatar imageAvatar3;
    // End of variables declaration//GEN-END:variables
}
